### ISSUE TITLE
Too Many users on RPCSETENV(TBICONN.PRW)

### ISSUE THREAD

**Issue by endersonmaia** [nginformatica/advpl-testsuite#6]
I needed to fix a problem identified in issue #3 , then, after successfully compiling the code and the `expect.prw` test case, I get the following error when running it.

![captura de tela 2018-02-23 as 14 36 51](https://user-images.githubusercontent.com/370/36608687-4f228bac-18a9-11e8-8405-d083d58fb1b0.png)

detailed log: https://gist.github.com/endersonmaia/a050ce17c79b05845f85899a4ce18d99

**Comment by vitorebatista** [comment]
@haskellcamargo please merge #2 ASAP

**Comment by haskellcamargo** [comment]
Closed by #2 via Vitão (@vitorebatista).
